{
  throw new UnsupportedOperationException("getUndo called on command that returned false for isUndoable");
}
