{
  try {
    qt.shutdown();
  }
 catch (  Exception e) {
    System.err.println("Exception: " + e.getMessage());
    e.printStackTrace();
    System.err.flush();
    throw new RuntimeException("Unexpected exception in shutdown",e);
  }
}
