{
  boolean foundException=false;
  try {
    testNestedinArrayAtLevelExtended(maxLevel,type);
  }
 catch (  SerDeException serdeEx) {
    foundException=true;
  }
  assertTrue("Got exception for exceeding nesting limit",foundException);
}
