{
  try {
    new ElapsedTimeLoggingWrapper<Void>(){
      @Override public Void invokeInternal() throws Exception {
        qt.shutdown();
        return null;
      }
    }
.invoke("Teardown done.",LOG,false);
  }
 catch (  Exception e) {
    System.err.println("Exception: " + e.getMessage());
    e.printStackTrace();
    System.err.flush();
    fail("Unexpected exception in shutdown");
  }
}
