def error(self):
    return self.__error
