{
  try {
    getConnection(HIVE_NON_EXISTENT_USER);
  }
 catch (  IOException e) {
    Assert.assertTrue(e.getMessage().contains("Login failure"));
  }
}
